package com.rentmaster.app.util;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.pdf.PdfDocument;
import android.os.Environment;
import android.widget.Toast;
import com.rentmaster.app.data.entity.Payment;
import com.rentmaster.app.data.entity.Tenant;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class PdfReportGenerator {
    public static File generateReceipt(Context context, Tenant tenant, Payment payment) {
        PdfDocument document = new PdfDocument();
        // A4 size in points (approx 595 x 842)
        int pageWidth = 595;
        int pageHeight = 842;
        PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create();
        PdfDocument.Page page = document.startPage(pageInfo);
        Canvas canvas = page.getCanvas();
        Paint paint = new Paint();

        // 1. Draw Border
        Paint borderPaint = new Paint();
        borderPaint.setStyle(Paint.Style.STROKE);
        borderPaint.setStrokeWidth(2);
        borderPaint.setColor(Color.DKGRAY);
        canvas.drawRect(20, 20, pageWidth - 20, pageHeight - 20, borderPaint);

        // 2. Header Section
        paint.setTextSize(24);
        paint.setTypeface(
                android.graphics.Typeface.create(android.graphics.Typeface.DEFAULT, android.graphics.Typeface.BOLD));
        paint.setColor(Color.BLACK);
        paint.setTextAlign(Paint.Align.CENTER);
        canvas.drawText("RENT RECEIPT", pageWidth / 2, 80, paint);

        paint.setTextSize(12);
        paint.setTypeface(android.graphics.Typeface.DEFAULT);
        paint.setTextAlign(Paint.Align.RIGHT);
        String receiptDate = FormatUtils.formatDate(System.currentTimeMillis());
        canvas.drawText("Date: " + receiptDate, pageWidth - 40, 120, paint);
        canvas.drawText("Receipt No: " + System.currentTimeMillis() % 100000, pageWidth - 40, 140, paint);

        // 3. Main Content (Received From)
        paint.setTextAlign(Paint.Align.LEFT);
        paint.setTextSize(14);

        int startY = 200;
        int startX = 50;
        int lineHeight = 30;

        canvas.drawText("Received From:    " + tenant.name, startX, startY, paint);
        startY += lineHeight;

        // 4. Amount Box
        Paint boxPaint = new Paint();
        boxPaint.setColor(Color.LTGRAY);
        boxPaint.setStyle(Paint.Style.FILL);
        canvas.drawRect(startX, startY, pageWidth - 50, startY + 60, boxPaint);

        paint.setTextSize(20);
        paint.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        String amountText = "Amount Paid:   " + FormatUtils.formatCurrency(payment.amount);
        // Vertically center text in box
        float textHeight = paint.descent() - paint.ascent();
        float textOffset = (textHeight / 2) - paint.descent();
        canvas.drawText(amountText, startX + 20, startY + 30 + textOffset, paint);

        startY += 100;

        // 5. Payment Details Table
        paint.setTextSize(14);
        paint.setTypeface(android.graphics.Typeface.DEFAULT);

        drawDetailRow(canvas, paint, "Payment For Month:", FormatUtils.formatDateWithMonth(payment.date), startX,
                startY);
        startY += lineHeight;

        drawDetailRow(canvas, paint, "Payment Mode:", payment.mode, startX, startY);
        startY += lineHeight;

        drawDetailRow(canvas, paint, "Reference / Notes:", payment.reference != null ? payment.reference : "-", startX,
                startY);
        startY += lineHeight * 2;

        // 6. Footer (Signature)
        canvas.drawLine(pageWidth - 250, startY + 50, pageWidth - 50, startY + 50, paint);
        paint.setTextAlign(Paint.Align.CENTER);
        canvas.drawText("Authorized Signatory", pageWidth - 150, startY + 70, paint);

        // 7. Branding
        paint.setTextAlign(Paint.Align.CENTER);
        paint.setTextSize(10);
        paint.setColor(Color.DKGRAY);
        canvas.drawText("Generated by RentMaster App", pageWidth / 2, pageHeight - 40, paint);

        document.finishPage(page);

        String fileName = "Receipt_" + tenant.name.replaceAll("\\s+", "_") + "_" + System.currentTimeMillis() + ".pdf";
        File file = new File(context.getExternalFilesDir(null), fileName);

        try {
            document.writeTo(new FileOutputStream(file));
            Toast.makeText(context, "Receipt generated: " + file.getAbsolutePath(), Toast.LENGTH_LONG).show();
            document.close();
            return file;
        } catch (IOException e) {
            e.printStackTrace();
            Toast.makeText(context, "Error generating PDF", Toast.LENGTH_SHORT).show();
            document.close();
            return null;
        }
    }

    private static void drawDetailRow(Canvas canvas, Paint paint, String label, String value, int x, int y) {
        paint.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);
        canvas.drawText(label, x, y, paint);
        paint.setTypeface(android.graphics.Typeface.DEFAULT);
        canvas.drawText(value, x + 200, y, paint);
    }
}
